//SPDX-License-Identifier: GNU GPLv3
pragma solidity ^0.8.15;

/**
 * @title Interface for autogenerated/ externally provided MiMC contract
 */
contract IMiMC {
    function MiMCpe7(uint256,uint256) public pure returns(uint256) {}
}